<?php
$data = array (
  0 => 
  array (
    'cat_id' => '1',
    'cat_name' => '鲜奶蛋糕',
    'measure_unit' => '个',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => 5,
  ),
  1 => 
  array (
    'cat_id' => '2',
    'cat_name' => '水果蛋糕',
    'measure_unit' => '个',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => 6,
  ),
  2 => 
  array (
    'cat_id' => '3',
    'cat_name' => '巧克力蛋糕',
    'measure_unit' => '个',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => 4,
  ),
  3 => 
  array (
    'cat_id' => '4',
    'cat_name' => '穆斯蛋糕',
    'measure_unit' => '个',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => 3,
  ),
  4 => 
  array (
    'cat_id' => '5',
    'cat_name' => '冰激凌蛋糕',
    'measure_unit' => '个',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '0',
    'goods_num' => 5,
  ),
  5 => 
  array (
    'cat_id' => '6',
    'cat_name' => '抹茶蛋糕',
    'measure_unit' => '个',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '6',
    'has_children' => '0',
    'goods_num' => 3,
  ),
  6 => 
  array (
    'cat_id' => '7',
    'cat_name' => '芝士蛋糕',
    'measure_unit' => '个',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '7',
    'has_children' => '0',
    'goods_num' => 3,
  ),
  7 => 
  array (
    'cat_id' => '8',
    'cat_name' => '无糖蛋糕',
    'measure_unit' => '个',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '8',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  8 => 
  array (
    'cat_id' => '17',
    'cat_name' => '情侣蛋糕',
    'measure_unit' => '个',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '11',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  9 => 
  array (
    'cat_id' => '14',
    'cat_name' => '生肖蛋糕',
    'measure_unit' => '个',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '12',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  10 => 
  array (
    'cat_id' => '11',
    'cat_name' => '圆形蛋糕',
    'measure_unit' => '个',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '13',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  11 => 
  array (
    'cat_id' => '18',
    'cat_name' => '节日蛋糕',
    'measure_unit' => '个',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '14',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  12 => 
  array (
    'cat_id' => '15',
    'cat_name' => '生日蛋糕',
    'measure_unit' => '个',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '15',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  13 => 
  array (
    'cat_id' => '12',
    'cat_name' => '多层蛋糕',
    'measure_unit' => '个',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '16',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  14 => 
  array (
    'cat_id' => '9',
    'cat_name' => '心形蛋糕',
    'measure_unit' => '个',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '17',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  15 => 
  array (
    'cat_id' => '19',
    'cat_name' => '庆典蛋糕',
    'measure_unit' => '个',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '18',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  16 => 
  array (
    'cat_id' => '16',
    'cat_name' => '祝寿蛋糕',
    'measure_unit' => '个',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '19',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  17 => 
  array (
    'cat_id' => '13',
    'cat_name' => '艺术蛋糕',
    'measure_unit' => '个',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '20',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  18 => 
  array (
    'cat_id' => '10',
    'cat_name' => '方形蛋糕',
    'measure_unit' => '个',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '21',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  19 => 
  array (
    'cat_id' => '20',
    'cat_name' => '儿童蛋糕',
    'measure_unit' => '个',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '22',
    'has_children' => '0',
    'goods_num' => 0,
  ),
);
?>